[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# REST API 프록시
[[redirects]]
  from = "/_be/api/*"
  to = "https://bobple-be.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = ":host" }

# WebSocket 프록시
[[redirects]]
  from = "/_be/ws/*"
  to = "https://bobple-be.onrender.com/ws/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = ":host" }
